### ISSUE TITLE
Failed to retrieve wine (lutris-5.7-x86_64)

### ISSUE THREAD

**Issue by rustybox** [balsamiq/balsamiq-wireframes-linux#1]
On Ubuntu 20.04 the closest wine version string I have available to this is

```
lutris-5.7-3    x86_64
```
What's the recommendation here, do I just create my own yaml installer using yours as a template?

Edit: a couple of extra questions

+ ~any chance of a native version at some point?~
+ ~Is AppImage a possibility? https://appimage.org/~

Looks like it's WPF so I guess stuck with wine until .net 6/MAUI :(

Sorry - pretty hype to have wireframes available to run regardless.

**Comment by rustybox** [comment]
As a workaround this seems to work fine

```
$ cp -r ~/.local/share/lutris/runners/wine/lutris-5.7-3-x86_64/ ~/.local/share/lutris/runners/wine/lutris-5.7-x86_64/

**Comment by balsamiqGozzi** [comment]
i did some tests then updated the script at the last lutris-5.7-3 version
thanks for the effort

**Comment by balsamiqGozzi** [comment]
> * ~any chance of a native version at some point?~
we haven't planned it yet, it will depend on how many installations there will be and on the future of wpf

> * ~Is AppImage a possibility? https://appimage.org/~
it could be a good idea, but wine uses a lot of 32bit libraries so likely it wouldn't be really portable. We haven't tested it yet

**Comment by rustybox** [comment]
WPF is almost 100% not coming, but this is presumably the future of C# + XAML https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/

In the meantime I wonder how hard it would be to port to https://avaloniaui.net/?

**Comment by lal12** [comment]
Not sure how the versioning works for lutris wine version, but I had to adjust it for me to be `lutris-5.7-10-x86_64`
