### ISSUE TITLE
Unknown trouble

### ISSUE THREAD

**Issue by Photon79** [balsamiq/balsamiq-wireframes-linux#10]
When I trying to start Balsamiq Wireframes I will go to login screen

System: Linux Mint 20.2 Mate
Lutris: 0.5.9.1

**Comment by alasdairnmanson** [comment]
Hi there @Photon79 and thanks for the issue.

Would you mind posting a screenshot of what you're seeing when you try to start the app and we'll do our best to help?

**Comment by balsamiqGozzi** [comment]
https://balsamiq.cloud/s2ow8jo/p1i706v

please follow these instructions to use bottle and chose the correct runner
