### ISSUE TITLE
Wine prefix creation is taking longer than expected

### ISSUE THREAD

**Issue by str** [balsamiq/balsamiq-wireframes-linux#11]
Following the instructions when installing via

```
lutris -i "https://raw.githubusercontent.com/balsamiq/balsamiq-wireframes-linux/master/balsamiq-wireframes-installer.json"
```
I get the following error:

```
Creating a win64 prefix in /home/str/Lutris/balsamiq-wireframes
Wine prefix creation is taking longer than expected...
```
I tried creating the folder before, and during the installation without success

**Comment by balsamiqGozzi** [comment]
Hi, at the moment the lutris installer seems broken, please try the following workaround:

1) install flatpak +  repositories
https://flatpak.org/setup/

2) install bottles from flatpak repo

3) download balsamiq wireframes setup.exe, create a new "bottle" with caffe-72 runner (different runners have problems) and install it "for all users"

**Comment by balsamiqGozzi** [comment]
closing this since already answered
