### ISSUE TITLE
Couldn't save the license to this computer on bottles.

### ISSUE THREAD

**Issue by fire** [balsamiq/balsamiq-wireframes-linux#12]
![image](https://user-images.githubusercontent.com/32321/198815199-69816a25-957a-4b69-8533-e024be2e4897.png)

**Comment by balsamiqGozzi** [comment]
Hi, did you install with the option "for all users?"
I just tried with last desktop version, bottles and caffe 7.2 runner and the license registration works just fine
Let me know

**Comment by fire** [comment]
I reverted to using Windows. :'(
