### ISSUE TITLE
Fonts very fuzzy

### ISSUE THREAD

**Issue by p-m-j** [balsamiq/balsamiq-wireframes-linux#2]
Fonts very fuzzy, bad on 1080p worse on 4K
![Screenshot from 2020-07-01 13-52-01](https://user-images.githubusercontent.com/2056399/86246002-3a928b80-bba2-11ea-8d82-7ddd284b9116.png)

**Comment by balsamiqGozzi** [comment]
it depends mainly on the hidpi display, you can change from lutris panel:

- select balsamiq wireframes
- click wine configuration
- select tab `graphics` and change screen resolution (for example from 96dpi to 144)

**Comment by str** [comment]
And now everything is super big and nothing fits in my HD screen. This is not a solution.

**Comment by VirginPereira** [comment]
Hi @str and sorry to hear that those steps didn't help.

Our Linux expert is out this week but we'd love to ask a few questions in the meantime to see if we can figure this out.

What Linux distribution are you using? 
Are you running the latest version of our tool (4.1.2)?

Also, could you share your display resolution? Any settings modified in the lutris application?

We'll do our best to help!

**Comment by rustybox** [comment]
@VirginPereira I'm not @str but i am the OP

I'm running Ubuntu 20.04

Looks garbage at both 1920x1080 and 3840x2160

**Comment by VirginPereira** [comment]
Thanks @rustybox! We'll try to reproduce the issue here and get back to you with more details.

**Comment by rustybox** [comment]
Cheers, I'm pretty desperate to give you guys some money :D but I right now it looks so ugly i'm happier with https://github.com/evolus/pencil

**Comment by balsamiqGozzi** [comment]
Hi @rustybox I've tested it on a new ubuntu sandbox and it look better than on your screenshot. (ubuntu 20.04, minimal desktop installation, tested on hidpi screen with 96/120/144 dpi)
Did you installed lutris adding the ppa or manually? (i tested it adding the ppa with `sudo add-apt-repository ppa:lutris-team/lutris`, then `sudo apt update`, then `sudo apt install lutris`)
If you installed it manually please try to install it through the repository because it install a lot of dependencies and fonts
How many dpi are you using for that setting? Are you using the standard ubuntu desktop? 
Thanks for your feedback

**Comment by rustybox** [comment]
```bash
$ sudo add-apt-repository ppa:lutris-team/lutris
$ sudo apt update
$ sudo apt --reinstall install lutris

Get:1 http://ppa.launchpad.net/lutris-team/lutris/ubuntu focal/main amd64 lutris amd64 0.5.7.1-202007191015~ubuntu20.04.1 [1,727 kB]
Fetched 1,727 kB in 0s (4,450 kB/s)
(Reading database ... 340285 files and directories currently installed.)
Preparing to unpack .../lutris_0.5.7.1-202007191015~ubuntu20.04.1_amd64.deb ...
Unpacking lutris (0.5.7.1-202007191015~ubuntu20.04.1) over (0.5.7.1-202007191015
~ubuntu20.04.1) ...
```

Still looks fuzzy, I have tried 96dpi @1080p and 144dpi @ 4K

![Screenshot from 2020-08-20 09-26-47](https://user-images.githubusercontent.com/2056399/90742201-4c053380-e2c7-11ea-8621-f1c13c53db98.png)

**Comment by balsamiqGozzi** [comment]
we have partially reproduced the issue, i'm reopening it as we are asking to devs the feasibility of a fallback font (we use segoeUI that currently is not installable on wine)

in the meantime, you can try to minimize the problems changing the font smoothing settings in wine:

- select balsamiq
- launch winetricks from lutris panel
- select default prefix
- change settings
- check fontfix and fontssmooth=rgb (if there's no relevant change, please try to set it to _disabled_)

**Comment by balsamiqGozzi** [comment]
another test you can try is to manuallly install segoeUI in this way:
`mkdir -p ~/.fonts/truetype/msttcorefonts/
cd ~/.fonts/truetype/msttcorefonts/
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/segoeui.ttf?raw=true -O segoeui.ttf # regular
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/segoeuib.ttf?raw=true -O segoeuib.ttf # bold
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/segoeuib.ttf?raw=true -O segoeuii.ttf # italic
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/segoeuiz.ttf?raw=true -O segoeuiz.ttf # bold italic
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/segoeuil.ttf?raw=true -O segoeuil.ttf # light
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/seguili.ttf?raw=true -O seguili.ttf # light italic
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/segoeuisl.ttf?raw=true -O segoeuisl.ttf # semilight
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/seguisli.ttf?raw=true -O seguisli.ttf # semilight italic
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/seguisb.ttf?raw=true -O seguisb.ttf # semibold
wget -q https://github.com/martinring/clide/blob/master/doc/fonts/seguisbi.ttf?raw=true -O seguisbi.ttf # semibold italic
fc-cache -f ~/.fonts/truetype/msttcorefonts/`

Let me know

**Comment by str** [comment]
Hi @balsamiqGozzi 

This is how it looks after installing the font

![image](https://user-images.githubusercontent.com/123817/91747585-af228000-eb7b-11ea-8bca-b520dd766ad1.png)

**Comment by rustybox** [comment]
I removed the wine prefix and ran lutris installer using bw.yml as at 0a87826, now running wireframes 4.1.2

Windows Version is set to Windows 10 (as set by bw.yml)
Set the suggested values in winetricks. can't see much difference.
Downloaded all the fonts listed above and ran fc-cache. can't see much difference.

**Comment by maddin79** [comment]
Hello, we are thinking about to buy this product. Is there a solution to this problem or will there be a fix soon?

Best
Martin

**Comment by balsamiqGozzi** [comment]
I recently also tried the "bottles" wine wrapper (flathub.org) with last wine 7.0 custom environment, but the rendering is still not pixel perfect on linux, I think that the problem is tied to wine libraries that still do not render perfectly the menus.
Officially we do support every balsamiq editor based on browser (we support chrome, edge, firefox on linux), as is balsamiq cloud, balsamiq for google drive, and integrations on different products (atlassian jira and confluence)

**Comment by richardbowman** [comment]
Yeah this is pretty rough - please as long-term customer would love to see this get resolved! Would be so nice to just be able to run the version from the browser in offline mode which looks perfect!
![Screenshot from 2023-04-20 08-43-07](https://user-images.githubusercontent.com/1568820/233369501-0d4a7e22-2c61-4d1c-a7ac-6b4c046f2879.png)

**Comment by balsamiqGozzi** [comment]
here are instructions to get the best possible result
https://balsamiq.cloud/s2ow8jo/p1i706v
