### ISSUE TITLE
Unreadable fonts

### ISSUE THREAD

**Issue by str** [balsamiq/balsamiq-wireframes-linux#4]
![image](https://user-images.githubusercontent.com/123817/89843386-c0a4d900-db35-11ea-83f5-6c750ca28fe6.png)

**Comment by rustybox** [comment]
Yeah, not sure why #2 was closed.

**Comment by balsamiqGozzi** [comment]
please try using bottles and these settings
https://balsamiq.cloud/s2ow8jo/p1i706v
