### ISSUE TITLE
no window shows up after 40 min

### ISSUE THREAD

**Issue by LuKC1024** [balsamiq/balsamiq-wireframes-linux#5]
Lutris 5.7.1, Ubuntu 20.04.1 LTS
Installed by clicking the "install" button on [https://lutris.net/games/balsamiq-wireframes/](https://lutris.net/games/balsamiq-wireframes/).

**Comment by balsamiqGozzi** [comment]
Hi, have you tried updating both lutris and doing another install with the new json config file?

**Comment by LuKC1024** [comment]
No. Sorry, I wish I have the resource to help. But I am no using Balsamiq any more, and I am not interested in project enough to reinstall and try the solution.
