### ISSUE TITLE
Problem registring

### ISSUE THREAD

**Issue by igorgue** [balsamiq/balsamiq-wireframes-linux#9]
Hi,

When I try to register the product via Help / Register

I get "Invalid License Key"

![image](https://user-images.githubusercontent.com/7014/120550444-1c389f80-c3b2-11eb-9fdd-cea504567df8.png)

Is there a way I can input this license manually?

**Comment by lgreen1133** [comment]
Hi @igorgue, 

Normally you would just copy and paste the license key as it was issued on your receipt. 

That error typically indicates the license key was entered incorrectly, perhaps there's an extra character. I can't see your license key here but to keep your data private, would you mind sending me the full screenshot and license key to sales@balsamiq.com? We can continue troubleshooting there. 

Thanks!
Liz
